const communityNameBlocklist = [
  'admin',
  'api',
  'app',
  'about',
  'blog',
  'cdn',
  'chat',
  'contact',
  'demo',
  'dev',
  'docs',
  'forum',
  'givepraise',
  'help',
  'legal',
  'mail',
  'news',
  'praise',
  'privacy',
  'prod',
  'security',
  'shop',
  'stage',
  'staging',
  'status',
  'store',
  'support',
  'test',
  'tos',
  'terms',
  'www',
  'account',
  'accounts',
  'affiliate',
  'billing',
  'book',
  'brand',
  'bug',
  'business',
  'career',
  'careers',
  'client',
  'clients',
  'code',
  'company',
  'compliance',
  'console',
  'control',
  'core',
  'corp',
  'customer',
  'dashboard',
  'data',
  'database',
  'directory',
  'download',
  'education',
  'email',
  'enterprise',
  'events',
  'faq',
  'feedback',
  'file',
  'files',
  'finance',
  'gateway',
  'git',
  'github',
  'guide',
  'host',
  'hosting',
  'hr',
  'info',
  'integration',
  'internal',
  'invoice',
  'intranet',
  'knowledgebase',
  'labs',
  'landing',
  'license',
  'login',
  'logs',
  'marketing',
  'media',
  'network',
  'official',
  'order',
  'partner',
  'partners',
  'payment',
  'portal',
  'press',
  'project',
  'projects',
  'promo',
  'protocol',
  'public',
  'register',
  'registration',
  'remote',
  'report',
  'reports',
  'resource',
  'resources',
  'sales',
  'sandbox',
  'server',
  'service',
  'services',
  'signin',
  'signup',
  'solutions',
  'source',
  'staff',
  'static',
  'storage',
  'system',
  'team',
  'tools',
  'training',
  'tutorial',
  'update',
  'user',
  'video',
  'web',
  'webinar',
  'wiki',
  'work',
];

/**
 * A valid community name is:
 * - lowercase
 * - minimum 4 characters
 * - maximum 30 characters
 * - only alphanumeric characters, underscores, dots, and hyphens
 * - cannot start with a dot or hyphen
 * - cannot end with a dot or hyphen
 * - cannot contain two dots, two hyphens, or two underscores in a row
 */

export function checkCommunityNameRegex(name: string): boolean {
  const pattern = /^[a-z0-9][a-z0-9_.-]{1,28}[a-z0-9]$/;
  return pattern.test(name);
}

export function isValidCommunityName(name: string): boolean {
  const isRegexValid = checkCommunityNameRegex(name);
  if (!isRegexValid) {
    return false;
  }
  return !communityNameBlocklist.includes(name);
}
