export enum AuthRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
  QUANTIFIER = 'QUANTIFIER',
  FORWARDER = 'FORWARDER',
  APIKEY_READWRITE = 'APIKEY_READWRITE',
  APIKEY_READ = 'APIKEY_READ',
  BOT_PRAISE_CREATE = 'BOT_PRAISE_CREATE',
}
