export enum AuthRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  USER = 'USER',
  QUANTIFIER = 'QUANTIFIER',
  FORWARDER = 'FORWARDER',
  APIKEY_READWRITE = 'APIKEY_READWRITE',
  APIKEY_READ = 'APIKEY_READ',
}
