export enum AuthRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
  QUANTIFIER = 'QUANTIFIER',
  FORWARDER = 'FORWARDER',
  APIKEY_READWRITE = 'APIKEY_READWRITE',
  APIKEY_READ = 'APIKEY_READ',
  DISCORD_BOT = 'DISCORD_BOT',
}
