export enum Permission {
  ApiKeyManage = 'apiKey:manage',
  ApiKeyView = 'apiKey:view',
  UsersFind = 'users:find',
  UsersExport = 'users:export',
  UserProfileUpdate = 'userProfile:update',
  UsersManageRoles = 'users:manageRoles',
  UserAccountsExport = 'userAccounts:export',
  UserAccountsView = 'userAccounts:view',
  UserAccountsCreate = 'userAccounts:create',
  UserAccountsUpdate = 'userAccounts:update',
  EventLogView = 'eventLog:view',
  PraiseView = 'praise:view',
  PraiseQuantify = 'praise:quantify',
  PraiseExport = 'praise:export',
  PeriodView = 'period:view',
  PeriodCreate = 'period:create',
  PeriodUpdate = 'period:update',
  PeriodAssign = 'period:assign',
  PeriodExport = 'period:export',
  QuantificationsExport = 'quantifications:export',
  SettingsView = 'settings:view',
  SettingsManage = 'settings:manage',
  PeriodSettingsView = 'periodSettings:view',
  PeriodSettingsManage = 'periodSettings:manage',
}
